"""
voice/tts.py
Text-to-Speech integration.
Converts the agent's text response into spoken audio bytes.
"""
from core.logging import get_logger
from core.config import get_settings

logger = get_logger(__name__)

async def generate_audio(text: str) -> bytes:
    """
    Takes text generated by the LLM and converts it to audio bytes.
    Currently mocked to return empty bytes to prevent API errors 
    if keys aren't set yet.
    """
    settings = get_settings()
    logger.info("Generating TTS audio for text: '%s...'", text[:30])
    
    # In a real implementation with ElevenLabs:
    # 1. Initialize ElevenLabs client
    # 2. Call the API: client.generate(text=text, voice="Rachel")
    # 3. Return the audio stream/bytes
    
    # Returning empty bytes for now as a placeholder
    return b""
