"""
voice/tts.py
Text-to-Speech integration.
Converts the agent's text response into spoken audio bytes.
"""
from core.logging import get_logger
from core.config import get_settings

logger = get_logger(__name__)

async def generate_audio(text: str) -> bytes:
    """
    Takes text generated by the LLM and converts it to audio bytes.
    Using ElevenLabs for ultra-realistic voice generation.
    """
    settings = get_settings()
    
    if not settings.ELEVENLABS_API_KEY:
        logger.warning("ELEVENLABS_API_KEY not set. Returning empty audio bytes.")
        return b""
        
    logger.info("Generating TTS audio for text: '%s...'", text[:30])
    
    try:
        from elevenlabs.client import ElevenLabs
        
        # Initialize the client
        client = ElevenLabs(api_key=settings.ELEVENLABS_API_KEY)
        
        # Generate audio using the turbo model
        audio_stream = client.text_to_speech.convert(
            text=text,
            voice_id="pNInz6obpgDQGcFmaJgB", # Adam
            model_id="eleven_turbo_v2_5"
        )
        
        # The API returns a generator, so we join all the chunks into a single byte string
        audio_bytes = b"".join(list(audio_stream))
        
        logger.debug("Successfully generated %d bytes of audio.", len(audio_bytes))
        return audio_bytes
        
    except Exception as e:
        logger.error("ElevenLabs TTS generation failed: %s", e)
        return b""
